In [61]:
!pip install numpy

In [62]:
import numpy as np

In [63]:
a=np.array([1,2,3,4])
b=np.array([3,5,2,5])

In [64]:
a+b

array([4, 7, 5, 9])

In [65]:
b-a

array([ 2,  3, -1,  1])

In [66]:
a*b

array([ 3, 10,  6, 20])

In [67]:
a/b

array([0.33333333, 0.4       , 1.5       , 0.8       ])

In [68]:
a//b

array([0, 0, 1, 0])

# broadcasting

In [69]:

#in broadcasting the values of rows or columns are being broadcasted 


In [70]:
ar1=np.arange(1,21).reshape(5,4)
ar1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [71]:
ar2=ar1.copy()
ar2
ar2=ar2*3              #multiplies all the values by 3
print(ar1)             #so here the 3 is broadcastedto all the elements
print(ar2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]


In [72]:
a1=np.array([2,3,4])
b1=np.array([
    [1],
    [2],
    [3]
    ])
print(a1)
print(b1)

[2 3 4]
[[1]
 [2]
 [3]]


In [73]:
print(a1*b1)  
#here also the values will be automatically broadcasted for multiplication

[[ 2  3  4]
 [ 4  6  8]
 [ 6  9 12]]


# deep copy and shallow copy
* shallow copy creates a new object but 
changes made in nested element "affects" the original
* deep copy creates a independent copy of the object and all the 
changes made in nested objec "doesn't affect" the original original

In [55]:
arr1=np.arange(1,21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# shallow copy  affects the original array
arr3=arr1
arr3[5]=100
print(arr3)
print(arr1)

[  1   2   3   4   5 100   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[  1   2   3   4   5 100   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]


In [ ]:
#deep copy  doesn't affect the original
arr2=arr1[:5]
arr2=arr2*3
print(arr2)
print(arr1)
print(arr3)   #arr1 and arr3 both refer to same address

[ 3  6  9 12 15]
[  1   2   3   4   5 100   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[  1   2   3   4   5 100   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]


# stacking the array

In [79]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [80]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [90]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [95]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [98]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]