In [2]:
import numpy as np

# array creation

In [ ]:
np.array([1,2,3,4,5,'prashi'])  #here the numpy will convert data to string datatype

array(['1', '2', '3', '4', '5', 'prashi'], dtype='<U21')

In [ ]:
np.array([1,3,3.2])  #all coverted to float

array([1. , 3. , 3.2])

In [26]:
a=np.array([[1,2,4,5],
           [1,2,46,3]])    #creating a 2d array
print(a)

[[ 1  2  4  5]
 [ 1  2 46  3]]


In [36]:
a3=np.array([[1,2,3],
             [6,4,2],
             [4.5,5.6,7.8]],dtype=complex)

In [37]:
a3

array([[1. +0.j, 2. +0.j, 3. +0.j],
       [6. +0.j, 4. +0.j, 2. +0.j],
       [4.5+0.j, 5.6+0.j, 7.8+0.j]])

In [34]:
a.shape

(2, 4)

In [20]:
a.ndim

2

In [21]:
a.dtype.name

'int64'

In [22]:
a.size

8

In [23]:
type(a)

numpy.ndarray

# generate array

In [44]:
arr=np.arange(50).reshape(5,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [62]:
arr1=np.arange(1,11,2)
print(arr1)
arr2=np.arange(1,12)
print(arr2)
np.arange(5)

[1 3 5 7 9]
[ 1  2  3  4  5  6  7  8  9 10 11]


array([0, 1, 2, 3, 4])

In [56]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [57]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [59]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [63]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

# random generation functions

In [75]:
np.random.rand(6)    #generate random numbers from 0 to 1

array([0.94211565, 0.78696943, 0.18108365, 0.03755933, 0.04128165,
       0.07417305])

In [89]:
np.random.randn(10) #generates random numbers from -3 to 3

array([ 0.56293837,  1.20451186, -1.19603061,  1.2750471 ,  1.08902842,
        0.41626933,  0.27570633, -0.42481723, -0.43809009,  0.7270707 ])

In [85]:
np.random.randint(1,20,10)

array([15, 14,  6,  5, 15,  5, 19, 11,  5, 14])

In [90]:
'''Here is a list of some useful NumPy functions and methods names ordered in 
categories. See routines for the full list.

Array Creation
arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity,
linspace, logspace, mgrid, ogrid, ones, ones_like, r_, zeros, zeros_like

Conversions
ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat

Manipulations
array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, 
hstack,ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, 
swapaxes, take,transpose, vsplit, vstack

Questions
all, any, nonzero, where

Ordering
argmax, argmin, argsort, max, min, ptp, searchsorted, sort

Operations
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, 
putmask, real,sum 

Basic Statistics
cov, mean, std, var

Basic Linear Algebra
cross, dot, outer, linalg.svd, vdot
'''

'Here is a list of some useful NumPy functions and methods names ordered in \ncategories. See routines for the full list.\n\nArray Creation\narange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity,\nlinspace, logspace, mgrid, ogrid, ones, ones_like, r_, zeros, zeros_like\n\nConversions\nndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat\n\nManipulations\narray_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, \nhstack,ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, \nswapaxes, take,transpose, vsplit, vstack\n\nQuestions\nall, any, nonzero, where\n\nOrdering\nargmax, argmin, argsort, max, min, ptp, searchsorted, sort\n\nOperations\nchoose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, \nputmask, real,sum \n\nBasic Statistics\ncov, mean, std, var\n\nBasic Linear Algebra\ncross, dot, outer, linalg.svd, vdot\n'

# some of the array attributes

In [91]:
arr=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
arr.shape     #to get the shape (row x col)

(3, 3)

In [ ]:
arr.size  #to get the total number of elements

9

In [ ]:
arr.ndim   # to get 

2

In [95]:
arr.dtype.name

'int64'

# some of the array methods

In [97]:
arr=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [98]:
arr.sum()

np.int64(45)

In [99]:
arr.min()

np.int64(1)

In [100]:
arr.max()


np.int64(9)

In [ ]:
arr.sum(axis=0)     #columnwise sum

array([12, 15, 18])

In [ ]:
arr.sum(axis=1)    #row wise sum

array([ 6, 15, 24])

In [105]:
arr.mean()

np.float64(5.0)

In [106]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax()   #index of maximum element in array

np.int64(8)

In [ ]:
arr.argmin()   #index of minimum element in array

np.int64(0)