In [1]:
import numpy as np

In [23]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [30]:
c=np.sum(s,axis=0)
r=np.sum(s,axis=1)
for i in c:
    if i != 45:
        print('sodoku is not valid')
        break
else:
    print('soduku is valid')

soduku is valid


In [34]:
for i in r:
    if i != 45:
        print('sodoku is not valid')
        break
else:
    print('soduku is valid')

soduku is valid


In [37]:
for i in range(0,9,3):
    for j in range(0,9,3):
        d=(s[i:i+3,j:j+3])
        x=d.sum()
        print(x)

45
45
45
45
45
45
45
45
45


In [46]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [47]:
data.shape

(5, 3)

In [53]:
np.mean(data[:,0])

np.float64(18.4)

In [55]:
x=data[:,1]
x

array([85, 92, 76, 65, 90])

In [59]:
y=np.max(data[:,2])
y

np.int64(95)

In [103]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [64]:
data[data[:,1]>90]


array([[19, 92, 88]])

In [72]:
data[:,1]+5

array([90, 97, 81, 70, 95])

In [75]:
len(data[data[:,0]<19])

3

In [76]:
np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [ ]:
data[(data[:,1] >=80) & (data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [91]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [105]:
data[:,2][data[:,2] < 75]=0
print(data)


[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65  0]
 [20 90 85]]
