In [2]:
import numpy as np

# vector(1D array) indexing and slicing

In [3]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[5]

np.int64(16)

In [5]:
arr[1:3]

array([12, 13])

In [6]:
arr[::-1]

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

# numpy indexing and slicing of matrix

In [7]:
ar1=np.arange(1,31).reshape(5,6)
ar1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [8]:
ar1[0]

array([1, 2, 3, 4, 5, 6])

In [9]:
ar1[2,4]

np.int64(17)

In [10]:
ar1[0:2,3:5]

array([[ 4,  5],
       [10, 11]])

In [11]:
ar1[2:5,4:6]

array([[17, 18],
       [23, 24],
       [29, 30]])

In [12]:
ar1[:,3]    #to selct full single column

array([ 4, 10, 16, 22, 28])

In [13]:
ar1[3,:]   # to select full single row 

array([19, 20, 21, 22, 23, 24])

# boolean indexing

In [20]:
arr=np.arange(20).reshape(4,5)
result=arr[(arr>5)& (arr<10)]
print(arr)
print(result)
res=arr[arr%2==0]
print(res)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
