In [1]:
import numpy as np

In [2]:
# matrix multiplication
a=np.array([
    [1,2],
    [3,4]
])

In [3]:
b=np.array([
    [5,6],
    [7,8]
])

In [4]:
a@b

array([[19, 22],
       [43, 50]])

In [5]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [6]:
a

array([[1, 2],
       [3, 4]])

In [7]:
a.transpose()

array([[1, 3],
       [2, 4]])